### ISSUE TITLE
博主的扫码很屌，使用了n个，感觉这个识别率最高

### ISSUE THREAD

**Issue by zj012611** [iluhcm/QrCodeScanner#1]
希望博主能继续优化项目，为我们这些小白做指导和帮助，我建议下一步可以去优化集成的便利性，比如这种：https://github.com/bingoogolapple/BGAQRCode-Android，他的识别率虽然没博主牛，但是这是我看到集成最方便的。
再次感谢楼主的源码，谢谢！

**Comment by iluhcm** [comment]
其实扫码识别率都差不多，只是我做了一些优化，精简了不常用的编码类型，所以相对来说速度上可能识别更快一些。

本来代码写得不是很好，不想开源的，但博客评论有一些人想看一下源码，我就传上来了。

就集成来说，我更推荐下载源码回去研读然后自己集成。只有知道扫码问题的根源在哪里，才能更好地解决扫码问题。

我有时间也会继续更新这个项目的，感谢反馈！
