### ISSUE TITLE
卡顿以及内存问题

### ISSUE THREAD

**Issue by HycHcl** [iluhcm/QrCodeScanner#10]
集成之后.启动稍微有点卡顿.退出时相当卡顿,主要是onPause的执行时间太长.使用leakcanary会出现内存溢出和gc lazy的问题

**Comment by iluhcm** [comment]
卡顿的确是有一点的，因为释放SurfaceView只能在主线程执行，否则有可能造成内存泄漏。后面我再优化一下吧。这一版的代码很老了。

**Comment by HycHcl** [comment]
嗯..我想自己集成zxing该怎么做..感觉有点难..项目要可以连续扫码,然后在当前页显示信息,不跳转新页面也不结束当前页...好忧心啊.

**Comment by iluhcm** [comment]
这个很简单啊，看一下源码，再改一下回调就可以了。

**Comment by HycHcl** [comment]
zxing的jar在哪下..在github上看到android包.感觉有点不像...扫描页面要定制的,那个取景框和背景怎么设置的啊...取景框要自定义...
