### ISSUE TITLE
看了你的博客，没评论功能，就写这里了

### ISSUE THREAD

**Issue by EspoirX** [iluhcm/QrCodeScanner#19]
看了你通知栏适配的问题，比较感兴趣，因为最近我也在研究，想互相学习一下。
说说我的一些见解和问题吧：
见解：7.0以后不会创建contentview，导致获取不了字体颜色，我的解决方案是先创建好自己的notification，然后获取自己notification中的字体颜色，获取方法跟文章中的一样，当然布局中的textcolor要跟随系统，不能写死，这我已经在项目里面得到验证，另外在判断颜色深浅的时候不知道你们是否也用这种方法：
```
    private static boolean isTextColorSimilar(int baseColor, int color) {
        int simpleBaseColor = baseColor | -16777216;
        int simpleColor = color | -16777216;
        int baseRed = Color.red(simpleBaseColor) - Color.red(simpleColor);
        int baseGreen = Color.green(simpleBaseColor) - Color.green(simpleColor);
        int baseBlue = Color.blue(simpleBaseColor) - Color.blue(simpleColor);
        double value = Math.sqrt((double) (baseRed * baseRed + baseGreen * baseGreen + baseBlue * baseBlue));
        return value < 180.0D;
    }
```
说一下这种方法能适配大部分，但是当颜色非常相近的时候是会有误差的，所以推荐用 v4 包里面的 ColorUtils.calculateLuminance() 方法判断。

疑问：我也很好奇通知栏的背景颜色是怎么改变的，文中你说到通过Notification.Builder.setColor()或者Notification.Builder.setColorized()设置，不过setColor只改变图标颜色，通知栏背景色一直都是白色，这我不懂怎么弄，不知道可否赐教一下。

最后，我对你说到的页面路由很感兴趣，期待开发出一个库出来。

**Comment by iluhcm** [comment]
1、我们已经全部使用系统的通知栏消息，不用ContentView了，所以不需要判断字体颜色了，不再做蛋疼地适配了。通知栏背景的颜色只有使用ContentView的时候，在布局里通过设置背景颜色来改变的。

2、页面路由的库暂时还不适合开源哈，我们内部实现了第二版基于Interceptor的路由，后续有时间会分享出来。如果短期内你们需要使用路由的话，可以参考一下ARouter，他们在这方面做得比较前卫了。

3、我的博客使用的是disqus评论系统，墙内访问可能有点问题。

有问题欢迎随时提出，也可以联系我的邮箱。
