### ISSUE TITLE
gradle编译版本会对扫描速度产生影响

### ISSUE THREAD

**Issue by 171428724** [iluhcm/QrCodeScanner#21]
demo里边使用的是：gradle2.2.3，
COMPILE_SDK_VERSION=android-24
BUILD_TOOLS_VERSION=25.0.0
MIN_SDK_VERSION=16
TARGET_SDK_VERSION=24

我使用的是：gradle:3.1.3
COMPILE_SDK_VERSION=27
MIN_SDK_VERSION=23
TARGET_SDK_VERSION=27

结果扫描支付宝二维码的速度慢了很多，把版本改回来速度就会很快，请问是什么原因？

**Comment by iluhcm** [comment]
跟编译版本关系应该不是很大吧。除了相机调用了系统API，其他的没有调用，可以查一查27对相机的API做了哪些修改。我们项目里现在用的是26，是没问题的。

**Comment by 171428724** [comment]
可能是厂家设备的关系吧，我用26编译了一下，速度还是慢了，和27编译的速度差不多，但是原版的demo扫支付宝二维码那速度真是快，谢谢博主

**Comment by iluhcm** [comment]
客气了，可以再查查原因是什么。
