### ISSUE TITLE
扫描界面的提示如果切换成英文会导致位置不对

### ISSUE THREAD

**Issue by tempersitu** [iluhcm/QrCodeScanner#8]
查看了代码发现是QrCodeFinderView里的drawText()有不够完善的地方. left坐标不准.  我修改了之后ok了.主要是加入以下方法:
public static int getWordLength(String value) {
        int valueLength = 0;
        String chinese = "[\u0391-\uFFE5]";
        for (int i = 0; i < value.length(); i++) {
            String temp = value.substring(i, i + 1);
            if (temp.matches(chinese)) {
                valueLength += 2;
            } else {
                valueLength += 1;
            }
        }
        return valueLength;
}

然后drawText里改为
int margin = 40;
mPaint.setColor(mTextColor);
mPaint.setTextSize(getResources().getDimension(R.dimen.text_size_13sp));
String text = getResources().getString(R.string.scan_text);
Paint.FontMetrics fontMetrics = mPaint.getFontMetrics();
float fontTotalHeight = fontMetrics.bottom - fontMetrics.top;
float offY = fontTotalHeight / 2 - fontMetrics.bottom;
 float newY = rect.bottom + margin + offY;
**float measureText = mPaint.measureText(text)+(mPaint.measureText(text)/ getWordLength(text)/2);**
float left = (ScreenUtils.getScreenWidth(mContext) - measureText) / 2;
canvas.drawText(text, left, newY, mPaint);

这样就中文或英文都居中了.

**Comment by iluhcm** [comment]
👍👍👍

这块代码在扫码过程中不是主要的点哈，参考着改就行。

**Comment by iluhcm** [comment]
如果方便的话，欢迎提个PR~
